<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>JavaScript unit test file</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <script src="../assets/jquery.min.js" type="text/javascript"></script>
  <script src="../assets/jsunittest.js" type="text/javascript"></script>

  <script src="../../src/ajax_mock/jquery.js" type="text/javascript"></script>

  <link rel="stylesheet" href="../assets/unittest.css" type="text/css" />

</head>
<body>

<div id="content">

  <div id="header">
    <h1>JavaScript unit test file</h1>
    <p>
      This file tests <strong>ajax_mock.js</strong>.
    </p>
  </div>

  <!-- Log output (one per Runner, via {testLog: "testlog"} option)-->
  <div id="testlog"></div>

  <!-- Put sample/test html here -->
  <div id="sample"></div>
</div>

<script type="text/javascript">
// <![CDATA[

  new Test.Unit.Runner({
    setup: function() {
      Test.Ajax.prepareMocks();
      this.working_url = "/working/url.json";
      this.nonworking_url = "/nonworking/url";
      this.completed = false;
      this.failed = false;
    },

    teardown: function() {
      Test.Ajax.clearMocks();
    },


    // Ajax call should complete
    testAjaxCallShouldComplete: function() { with(this) {
      self = this;
      Test.Ajax.setupMock(working_url, function(request, response) {
        response.responseJSON = "data";
        request.complete(response);
      });
      $.ajax({
        url: working_url,
        type: "get",
        complete: function() {
          self.completed = true;
        },
        error: function() {
          self.error("onFailure should not be called");
        }});
      wait(100, function() {
        assert(self.completed, 'onComplete should have been called');
      });
    }},

    // AjaxCallShouldFail
    testAjaxCallShouldFail: function() { with(this) {
      self = this;
      Test.Ajax.setupMock(nonworking_url, function(request, response) {
        request.error(response);
      })
      $.ajax({
        url: nonworking_url,
        type: "get",
        completed: function() {
          self.error("onComplete should not be called");
        },
        error: function() {
          self.failed = true;
        }
      });
      wait(100, function() {
        assert(self.failed, 'onFailure should have been called');
      });
    }},
    
    "test that only on ajax callback invoked if multiple mocks": function() { with(this) {
      var one_called = false;
      var two_called = false;
      Test.Ajax.setupMock("/one", function(request, response) {
        one_called = true;
      });
      Test.Ajax.setupMock("/two", function(request, response) {
        two_called = true;
      });
      $.get('/two');
      assert(!one_called, '/one should not be invoked');
      assert(two_called);
    }},

    
  });
// ]]>
</script>
</body>
</html>